[package]
name = "demo-egui"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eframe = "0.33.3"
log = "0.4"
env_logger = "0.11"
egui-system-fonts = { path = "../egui-system-fonts" }
